### ISSUE TITLE
Just A Little Doubt

### ISSUE THREAD

**Issue by Harshal0506** [payalpatra/Sms-Sender#1]
Dii Why Did you included Crypto.js in your index.js file

( I Am not able to understand it purpose)
AnyWays Thank you for providing many such great projects for my Learning Purpose
Thanks

**Comment by payalpatra** [comment]
Hello Harshal :) 
Basically, I had planned to hash the message and save all the hash messages in the DB. But later on, I decided to keep things simple and didn't implement that. (So, Crypto.js isn't serving any purpose. )

Good To See You Learning in such detail :)

**Comment by Harshal0506** [comment]
Thank you for clearing it 😃
Thanks again for some amazing Repositories
